name: Setup
description: Setup tools and runs pnpm install

runs:
  using: composite
  steps:
    - name: Setup Nix
      uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Nix binary cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(nix develop .#ci --command pnpm store path --silent)" >> "$GITHUB_OUTPUT"
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
    - name: Setup corepack
      shell: bash
      run: nix develop .#ci --command corepack install
    - name: Install dependencies
      shell: bash
      run: nix develop .#ci --command pnpm install --frozen-lock
