name: Setup
description: Setup tools and runs pnpm install

runs:
  using: composite
  steps:
    - name: Setup Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: asa1984/ci-binary-cache-action@v1
      with:
        packages: .#ci
    - name: Install requirements
      shell: bash
      run: nix profile install .#ci
    - name: Setup corepack
      shell: bash
      run: corepack install
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
    - name: Setup Turborepo cache
      uses: rharkor/caching-for-turbo@v1.5
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lock
