name: Setup
description: Setup tools

runs:
  using: composite
  steps:
    - name: Setup Nix
      uses: cachix/install-nix-action@v27
    #   uses: DeterminateSystems/nix-installer-action@v14
    - name: Setup Nix binary cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Get pnpm store path
      shell: bash
      run: echo "$(nix develop .#ci --command pnpm store path)" >> "$GITHUB_OUTPUT"
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: nix develop .#ci --command pnpm install --frozen-lock
