packages:
  - "packages/*"

catalog:
  # TypeScript
  typescript: ~5.7.2

  # Development tools
  chokidar-cli: ^3.0.0
  rimraf: ^5.0.10
  tsx: ^4.19.2

  # Core libraries
  zod: ^3.23.8
  ulidx: ^2.4.1

  # GraphQL
  graphql: ^16.9.0

  # Backend
  hono: ^3.12.12

  # Frontend
  next: ^14.2.14
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1

  # CSS
  "@pandacss/dev": ^0.22.1

  # Node.js
  "@types/node": ^22.10.1

  # Cloudflare
  wrangler: ^3.91.0
  "@cloudflare/workers-types": ^4.20241004.0
