name = "asa1984-api"
compatibility_date = "2023-01-01"

[vars]
API_TOKEN = "<your api token>"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "<your bucket name>"

[[d1_databases]]
binding = "DB"
database_name = "<your db name>"
database_id = "<your db id>"
