name = "asa1984-api"
compatibility_date = "2023-01-01"

# [vars]
# API_TOKEN = "${API_TOKEN}"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "asa1984-image"

[[d1_databases]]
binding = "DB"
database_name = "asa1984-blog"
database_id = "79856d54-a73b-481f-bb34-7a56ba8b993b"
