[package]
name = "trashbox_domain"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
thiserror.workspace = true
url.workspace = true
