schema: ./schema/*.graphql
documents: ./src/**/*.graphql
extensions:
  nitrogql:
    plugins:
      - "nitrogql:model-plugin"
      - "nitrogql:graphql-scalars-plugin"
    generate:
      mode: with-loader-ts-5.0
      schemaOutput: ./src/generated/schema.d.ts
      serverGraphqlOutput: ./src/generated/graphql.ts
      resolversOutput: ./src/generated/resolvers.d.ts
      schemaModuleSpecifier: "@/generated/schema"
