name: Deployment

on:
  push:
    paths-ignore:
      - "packages/cli/**"
      - "packages/frontend/**"
    branches:
      - main

env:
  DOTENV_PRIVATE_KEY_PRODUCTION: ${{secrets.DOTENV_PRIVATE_KEY_PRODUCTION}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy
        run: nix develop .#ci --command pnpm run deploy
