name: Deploy secrets

on:
  push:
    paths:
      - .env.production
    branches:
      - main

env:
  DOTENV_PRIVATE_KEY_PRODUCTION: ${{secrets.DOTENV_PRIVATE_KEY_PRODUCTION}}

permissions:
  contents: read

jobs:
  deploy-secret:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy secrets
        run: nix develop .#ci --command pnpm run deploy:secret
