name: Deployment

on:
  push:
    paths-ignore:
      - "packages/cli/**"
      - README.md
    branches:
      - main

env:
  DOTENV_PRIVATE_KEY_PRODUCTION: ${{secrets.DOTENV_PRIVATE_KEY_PRODUCTION}}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy
        run: nix develop .#ci --command pnpm run deploy
      - name: Deploy frontend
        run: |
          nix develop .#ci --command pnpm run build:frontend
          nix develop .#ci --command pnpm run deploy:frontend
