name: Deploy secrets

on:
  push:
    paths:
      - .env.production
    branches:
      - main

env:
  DOTENV_PRIVATE_KEY_PRODUCTION: ${{secrets.DOTENV_PRIVATE_KEY_PRODUCTION}}

jobs:
  deploy-secret:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Typecheck
        run: nix develop .#ci --command pnpm run deploy:secret
