name: Migrate Cloudflare D1

on:
  push:
    paths:
      - "packages/drizzle/migrations/**"
      - ".github/workflows/migrate.yaml"
    branches:
      - main

env:
  DOTENV_PRIVATE_KEY_PRODUCTION: ${{secrets.DOTENV_PRIVATE_KEY_PRODUCTION}}

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Migrate
        run: nix develop .#ci --command pnpm run migrate:prod
