name: Migrate Cloudflare D1

on:
  push:
    paths:
      - "packages/drizzle/migrations/**"
      - ".github/workflows/migrate.yaml"
    branches:
      - main

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Migrate
        run: nix develop .#ci --command pnpm run migrate:prod
